---
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14
    commit-message:
      prefix: ⬆
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"
